[package]
name = "virtualbutfake/fusionutils"
description = "A collection of utilities for working with Fusion 0.2"
version = "0.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
fusion = "elttob/fusion@0.2.0"